import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowLeft, Check, CreditCard, Edit3, Minus, Moon, Package, Plus, RefreshCw, Search, ShoppingCart, Sun, Trash2, X } from 'lucide-react';
import './styles.css';

const API = import.meta.env.VITE_API_URL || 'http://localhost:4001/api';

function Header({ dark, setDark, openCatalog, cartCount }) {
  return <header className="app-header"><a className="brand-lockup" href="/">KRISH <span>COUNTER</span><small>RETAIL OPERATIONS</small></a><nav><a className={location.pathname === '/' ? 'active' : ''} href="/">Inventory</a><a className={location.pathname === '/cart' ? 'active' : ''} href="/cart">Cart <span className="nav-count">{cartCount}</span></a><a className={location.pathname === '/orders' ? 'active' : ''} href="/orders">Orders</a></nav><div className="header-actions"><button className="manage-button" onClick={openCatalog}><Plus size={15}/> Manage catalog</button><a className="cart-link" href="/cart" aria-label={`Open cart with ${cartCount} items`}><ShoppingCart size={16}/><span>{cartCount}</span></a><button className="theme-toggle" onClick={() => setDark(!dark)} title={`Switch to ${dark ? 'light' : 'dark'} theme`}>{dark ? <Sun size={17}/> : <Moon size={17}/>}<span>{dark ? 'Light' : 'Dark'}</span></button></div></header>;
}

function CartPage({ cart, updateQuantity, remove, total, order, reserve, pay, message }) {
  return <section className="cart-page"><a className="back-link" href="/"><ArrowLeft size={15}/> Back to inventory</a><div className="cart-page-heading"><div><p className="kicker">YOUR CART / {cart.reduce((sum, item) => sum + item.quantity, 0).toString().padStart(2, '0')} ITEMS</p><h1>Ready to check out.</h1><p className="lede">Review your selection, reserve stock, and complete the mock payment.</p></div><div className="cart-total-large"><span>Order total</span><strong>${Number(order?.total || total).toFixed(2)}</strong></div></div>{cart.length ? <div className="cart-layout"><div className="cart-items">{cart.map((item) => <article className="cart-item" key={item.productId}><div className="cart-item-art"><Package size={22}/></div><div className="cart-item-info"><strong>{item.name}</strong><span>${Number(item.price).toFixed(2)} each</span></div><div className="quantity-control"><button onClick={() => updateQuantity(item.productId, item.quantity - 1)} aria-label={`Decrease ${item.name}`}><Minus size={14}/></button><span>{item.quantity}</span><button onClick={() => updateQuantity(item.productId, item.quantity + 1)} aria-label={`Increase ${item.name}`}><Plus size={14}/></button></div><strong className="cart-item-total">${(item.price * item.quantity).toFixed(2)}</strong><button className="remove-item" onClick={() => remove(item.productId)} aria-label={`Remove ${item.name}`}><Trash2 size={16}/></button></article>)}</div><aside className="cart-summary"><p className="kicker">SUMMARY</p><h2>One last look.</h2>{cart.map((item) => <div className="line" key={item.productId}><span>{item.name} <small>× {item.quantity}</small></span><strong>${(item.price * item.quantity).toFixed(2)}</strong></div>)}<div className="total"><span>Total</span><strong>${Number(order?.total || total).toFixed(2)}</strong></div>{!order ? <button className="primary" onClick={reserve}><CreditCard size={17}/> Reserve stock</button> : order.status === 'reserved' ? <div className="payment"><p className="muted">Reservation active for five minutes.</p><button className="success" onClick={() => pay('success')}><Check size={16}/> Approve payment</button><button className="danger" onClick={() => pay('failure')}><X size={16}/> Fail payment</button><button className="ghost" onClick={() => pay('timeout')}>Simulate timeout</button></div> : <div className="payment-result"><span className="muted">Payment status</span><strong className={`status ${order.status}`}>{order.status}</strong></div>}{message && <p className="message">{message}</p>}</aside></div> : <div className="empty-cart"><ShoppingCart size={32}/><h2>Your cart is empty.</h2><p className="muted">Add something useful from the inventory to get started.</p><a className="primary" href="/">Browse inventory</a></div>}</section>;
}

function Inventory({ products, load, add, query, setQuery }) {
  const shown = products.filter((product) => product.name.toLowerCase().includes(query.toLowerCase()));
  return <section className="layout"><div><div className="section-head"><div><p className="kicker">LIVE INVENTORY / {products.length.toString().padStart(2, '0')} SKUS</p><h2>Available now</h2></div><div className="section-tools"><label className="search-box"><Search size={15}/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find an item"/></label><button className="icon-button" onClick={load} title="Refresh inventory"><RefreshCw size={18}/></button></div></div><div className="products">{shown.map((product, index) => <article className="product" style={{ '--delay': `${index * 70}ms` }} key={product.id}>{product.imageUrl ? <img className="product-image" src={product.imageUrl} alt={product.name}/> : <div className="product-icon"><Package size={22}/><span>{String(index + 1).padStart(2, '0')}</span></div>}<div className="product-meta"><span className={product.stock < 5 ? 'low-stock' : ''}>{product.stock < 5 ? 'Low stock' : 'In stock'}</span><span>{product.stock} units</span></div><h3>{product.name}</h3><p className="price">${Number(product.price).toFixed(2)}</p><div className="stock"><span>Ready to sell</span><button onClick={() => add(product)} disabled={!product.stock}>Add to cart</button></div></article>)}</div>{!shown.length && <div className="empty-state"><Package size={25}/><p>No inventory matches “{query}”.</p></div>}</div></section>;
}

function Orders({ orders, cancel }) {
  return <section className="orders-page"><div className="page-intro"><div><p className="kicker">TRANSACTION LOG / {orders.length.toString().padStart(2, '0')} RECORDS</p><h1>Order history</h1><p className="lede">A clear record of every reservation and payment outcome.</p></div><div className="stat-chip"><span>Today</span><strong>{orders.filter((order) => order.status === 'paid').length} paid</strong></div></div>{orders.length ? <div className="order-list">{orders.map((order) => <article className="order" key={order.id}><div><strong>#{order.id.slice(0, 8)}</strong><span>{(order.items || []).map((item) => `${item.name || item.id} × ${item.quantity}`).join(', ')}</span></div><span className={`status ${order.status}`}>{order.status}</span><strong>${Number(order.total).toFixed(2)}</strong>{['reserved', 'paid'].includes(order.status) && <button className="cancel-order" onClick={() => cancel(order.id)}>Cancel</button>}</article>)}</div> : <div className="empty-state"><Package size={25}/><p>No orders have been recorded yet.</p></div>}</section>;
}

function ProductForm({ product, onSave, onClose }) {
  const [form, setForm] = useState(product || { id: '', name: '', price: '', stock: '', imageUrl: '' });
  const change = (key) => (event) => setForm({ ...form, [key]: event.target.value });
  return <form className="product-form" onSubmit={(event) => { event.preventDefault(); onSave({ ...form, price: Number(form.price), stock: Number(form.stock) }); }}><div className="form-heading"><div><p className="kicker">{product ? 'EDIT SKU' : 'NEW SKU'}</p><h2>{product ? 'Update product' : 'Add product'}</h2></div><button type="button" className="close-button" onClick={onClose}><X size={18}/></button></div><label>Product ID<input required disabled={Boolean(product)} value={form.id} onChange={change('id')} placeholder="e.g. ceramic-mug"/></label><label>Name<input required value={form.name} onChange={change('name')} placeholder="Product name"/></label><div className="form-row"><label>Price<input required type="number" min="0" step="0.01" value={form.price} onChange={change('price')} placeholder="0.00"/></label><label>Stock<input required type="number" min="0" value={form.stock} onChange={change('stock')} placeholder="0"/></label></div><label>Image URL <span className="optional">optional</span><input value={form.imageUrl || ''} onChange={change('imageUrl')} placeholder="https://..."/></label><button className="primary" type="submit"><Check size={16}/> {product ? 'Save changes' : 'Create product'}</button></form>;
}

function CatalogDialog({ products, saveProduct, removeProduct, close }) {
  const [editing, setEditing] = useState(null);
  return <dialog open className="catalog-dialog"><div className="catalog-panel"><div className="catalog-top"><div><p className="kicker">CATALOG CONTROL</p><h2>Manage products</h2></div><button className="close-button" onClick={close}><X size={18}/></button></div>{editing ? <ProductForm product={editing.id ? editing : null} onSave={(product) => { saveProduct(product, editing.id); setEditing(null); }} onClose={() => setEditing(null)}/> : <><button className="new-product" onClick={() => setEditing({})}><Plus size={16}/> Add new product</button><div className="catalog-list">{products.map((product) => <div className="catalog-row" key={product.id}><div><strong>{product.name}</strong><span>{product.id} · {product.stock} in stock</span></div><strong>${Number(product.price).toFixed(2)}</strong><button title={`Edit ${product.name}`} onClick={() => setEditing(product)}><Edit3 size={16}/></button><button className="delete-button" title={`Delete ${product.name}`} onClick={() => removeProduct(product.id)}><Trash2 size={16}/></button></div>)}</div></>}</div></dialog>;
}

function App() {
  const [products, setProducts] = useState([]); const [orders, setOrders] = useState([]); const [cart, setCart] = useState(() => JSON.parse(localStorage.getItem('counter-cart') || '[]')); const [order, setOrder] = useState(null); const [message, setMessage] = useState(''); const [query, setQuery] = useState(''); const [catalogOpen, setCatalogOpen] = useState(false); const [dark, setDark] = useState(() => localStorage.getItem('counter-theme') === 'dark');
  const request = async (path, options) => { const response = await fetch(`${API}${path}`, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Request failed'); return data; };
  const load = () => request('/products').then(setProducts).catch((error) => setMessage(error.message));
  const loadOrders = () => request('/orders').then(setOrders).catch((error) => setMessage(error.message));
  useEffect(() => { load(); loadOrders(); }, []); useEffect(() => { localStorage.setItem('counter-cart', JSON.stringify(cart)); }, [cart]); useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('counter-theme', dark ? 'dark' : 'light'); }, [dark]);
  const add = (product) => setCart((items) => { const existing = items.find((item) => item.productId === product.id); return existing ? items.map((item) => item.productId === product.id ? { ...item, quantity: item.quantity + 1 } : item) : [...items, { productId: product.id, name: product.name, price: product.price, quantity: 1 }]; });
  const updateQuantity = (productId, quantity) => setCart((items) => quantity > 0 ? items.map((item) => item.productId === productId ? { ...item, quantity } : item) : items.filter((item) => item.productId !== productId));
  const remove = (productId) => setCart((items) => items.filter((item) => item.productId !== productId));
  const reserve = async () => { try { const data = await request('/orders/reserve', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ items: cart, paymentKey: crypto.randomUUID() }) }); setOrder(data); setMessage('Stock reserved for five minutes. Choose a mock payment outcome.'); load(); } catch (error) { setMessage(error.message); } };
  const pay = async (outcome) => { try { const data = await request(`/orders/${order.id}/pay`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ outcome }) }); setOrder(data); setMessage(`Order is ${data.status}.`); load(); loadOrders(); } catch (error) { setMessage(error.message); } };
  const cancel = async (id) => { try { await request(`/orders/${id}/cancel`, { method: 'POST' }); setMessage('Order cancelled and stock returned.'); load(); loadOrders(); } catch (error) { setMessage(error.message); } };
  const saveProduct = async (product, id) => { try { const data = await request(id ? `/products/${id}` : '/products', { method: id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(product) }); setProducts((items) => id ? items.map((item) => item.id === id ? data : item) : [...items, data]); setMessage(id ? 'Product updated.' : 'Product created.'); } catch (error) { setMessage(error.message); } };
  const removeProduct = async (id) => { if (!window.confirm('Delete this product?')) return; try { await request(`/products/${id}`, { method: 'DELETE' }); setProducts((items) => items.filter((item) => item.id !== id)); setMessage('Product deleted.'); } catch (error) { setMessage(error.message); } };
  const total = cart.reduce((sum, item) => sum + item.price * item.quantity, 0); const isOrders = window.location.pathname === '/orders'; const isCart = window.location.pathname === '/cart'; const cartCount = cart.reduce((sum, item) => sum + item.quantity, 0);
  return <main><Header dark={dark} setDark={setDark} openCatalog={() => setCatalogOpen(true)} cartCount={cartCount}/>{isOrders ? <Orders orders={orders} cancel={cancel}/> : isCart ? <CartPage cart={cart} updateQuantity={updateQuantity} remove={remove} total={total} order={order} reserve={reserve} pay={pay} message={message}/> : <><section className="hero"><div><p className="eyebrow">OPERATIONS / TODAY</p><h1>Krish <span>Counter</span></h1><p className="lede">A calm, precise workspace for keeping every shelf and sale in balance.</p><div className="hero-stats"><span><strong>{products.length}</strong> active SKUs</span><span><strong>{orders.length}</strong> orders logged</span></div></div><div className="hero-art"><div className="hero-grid"></div><span className="hero-art-label">INVENTORY / 01</span><div className="hero-ring"></div></div></section><Inventory products={products} load={load} add={add} query={query} setQuery={setQuery}/></>}{catalogOpen && <CatalogDialog products={products} saveProduct={saveProduct} removeProduct={removeProduct} close={() => setCatalogOpen(false)}/>}</main>;
}

createRoot(document.getElementById('root')).render(<App />);
